# Email Configuration
mail.default.address=ace.bank.info@gmail.com
mail.google.app.password=clwg sqyn uvoz pvnz

# Database Configuration
db.url=jdbc:mysql://mysql-dca303d-venumadhava48-6082.h.aivencloud.com:10520/defaultdb?ssl-mode=REQUIRED
db.user=avnadmin
db.password=Venu@7893
db.script.path=/sql/schema_initializer.sql
db.mysql.driver=com.mysql.cj.jdbc.Driver

# SMTP Server Settings
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.connection-timeout=5000
mail.smtp.timeout=5000

# Twilio SMS Configuration
twilio.account.sid=your_twilio_account_sid_here
twilio.auth.token=your_twilio_auth_token_here
twilio.phone.number=+1234567890
