# Email Configuration
mail.default.address=${MAIL_DEFAULT_ADDRESS}
mail.google.app.password=${MAIL_GOOGLE_APP_PASSWORD}

# Database Configuration
db.url=jdbc:mysql://mysql-dca303d-venumadhava48-6082.h.aivencloud.com:10520/defaultdb?ssl-mode=REQUIRED
db.user=avnadmin
db.password=${DB_PASSWORD}
db.script.path=/sql/schema_initializer.sql
db.mysql.driver=com.mysql.cj.jdbc.Driver

# SMTP Server Settings
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.connection-timeout=5000
mail.smtp.timeout=5000

# Twilio SMS Configuration
twilio.account.sid=${TWILIO_ACCOUNT_SID}
twilio.auth.token=${TWILIO_AUTH_TOKEN}
twilio.phone.number=${TWILIO_PHONE_NUMBER}
