package com.acebank.lite.controllers;

import com.acebank.lite.models.LoginResult;
import com.acebank.lite.models.User;
import com.acebank.lite.service.BankService;
import com.acebank.lite.service.BankServiceImpl;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import lombok.extern.java.Log;

import java.io.IOException;
import java.io.Serial;
import java.util.ArrayList;
import java.util.Optional;

@Log
@WebServlet("/signup")
public class SignUp extends HttpServlet {
    @Serial
    private static final long serialVersionUID = 1L;

    // Use the service, not the DAO directly
    private final BankService bankService = new BankServiceImpl();

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        request.getRequestDispatcher("/sign-up.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        // 1. Extract Data
        String firstName = request.getParameter("firstName");
        String lastName = request.getParameter("lastName");
        String aadharStr = request.getParameter("aadharNumber");
        String identifier = request.getParameter("identifier");
        String password = request.getParameter("password");
        String transactionPin = request.getParameter("transactionPin");

        String email = null;
        String phone = null;
        if (identifier != null && identifier.contains("@")) {
            email = identifier;
        } else if (identifier != null) {
            phone = identifier;
        }

        try {
            // 2. Create the immutable Record
            User newUser = new User(
                    null, // ID generated by DB
                    firstName,
                    lastName,
                    aadharStr,
                    email,
                    phone,
                    password, // Note: Should be hashed in the Service layer
                    transactionPin, // Note: Should be hashed in the Service layer
                    null // CreatedAt generated by DB
            );

            // 3. Call Service to handle logic
            Optional<LoginResult> resultOpt = bankService.registerUser(newUser);

            if (resultOpt.isPresent()) {
                var details = resultOpt.get();
                HttpSession session = request.getSession();

                // 4. Set Session Attributes
                session.setAttribute("accountNumber", details.accountNumber());
                session.setAttribute("firstName", details.firstName());
                session.setAttribute("email", details.email());
                session.setAttribute("balance", details.balance());
                session.setAttribute("transactionDetailsList", new ArrayList<>());

                // request.getRequestDispatcher("/WEB-INF/views/Home.jsp").forward(request,
                // response);
                // REDIRECT: Tells browser "Go to /home using GET"
                response.sendRedirect(request.getContextPath() + "/home");
            } else {
                response.sendRedirect(request.getContextPath()
                        + "/sign-up.jsp?error=Signup+failed.+Email,+Phone,+or+Aadhaar+may+already+exist.");
            }

        } catch (Exception e) {
            log.severe("SignUp Servlet Error: " + e.getMessage());
            response.sendRedirect(request.getContextPath() + "/sign-up.jsp?error=System+Error.+Please+try+again.");
        }
    }
}
